# Generated by Django 4.1.6 on 2023-02-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Article')),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
                ('author', models.CharField(default='Author', max_length=40, verbose_name='Author')),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Held', 'HELD')], default='Ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Crated at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
