# Generated by Django 4.1.6 on 2023-02-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Text'),
        ),
    ]
