# Generated by Django 4.1.6 on 2023-02-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_tasks_description_alter_tasks_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Description', max_length=250, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Crated at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Comments', to='todoapp.tasks', verbose_name='Task')),
            ],
        ),
    ]
