# Generated by Django 4.1.6 on 2023-02-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='text',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
