# Generated by Django 4.1.6 on 2023-03-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_project_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task_id',
        ),
        migrations.AddField(
            model_name='project',
            name='tasks_id',
            field=models.ManyToManyField(related_name='projects', to='todoapp.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todoapp.project'),
        ),
    ]
