# Generated by Django 4.1.6 on 2023-03-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_initial'),
    ]

    operations = [
    ]
